<a href="https://colab.research.google.com/github/Nkemn1/ALT-School-Assignments/blob/hello-world-images/Work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program that prints your full name, your favourite hobby, and a one-line
description about yourself.

In [2]:

print("My name is Nkem Nwafor.")
print("My favourite hobby is reading and swimming.")
print("I am an undergraduate student currently dabbling in Data science")

My name is Nkem Nwafor.
My favourite hobby is reading and swimming.
I am an undergraduate student currently dabbling in Data science

State two differences between a Python list and a dictionary. Give an example of each.

In [4]:
#A python list can be described  as a collection of numbers or items in square brackets
list_string = ['orange', 'mango', 'cherry']
print (list_string)

# A dictionary ???

['orange', 'mango', 'cherry']

Imagine you have a DataFrame called sales_data. - - -
Show the number of rows and columns in the DataFrame.
Display the top 3 rows.
Check which columns have missing valu

In [9]:
from google.colab import files
files = files.upload()
import pandas as pd
import numpy as np

Saving iris.csv to iris (1).csv

In [14]:
iris = pd.read_csv('iris.csv')

In [16]:
df = pd.DataFrame(iris)
df.head(3)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [19]:
df.isnull()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [21]:
print(iris)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Write a Python program that takes an integer input and checks if it’s a multiple of 3 or
not. Print an appropriate message.

In [26]:
input = 4
if input % 3 == 0:
  print(f"{input} is a multiple of 3")
else:
  print(f"{input} is not a multiple of 3")

4 is not a multiple of 3

Given a list marks = [75, 88, 92, 60, 70], write code to: -
Calculate the average (mean) score. -
Print the result.

In [27]:
your_list = [75, 88, 92, 60, 70]
mean = sum(your_list)/len(your_list)
print (mean)

77.0

Create a Function to Calculate the Square of a Number -
Define a function square_num(num) that takes a number and returns its square. -
Test the function with at least two numbers.

In [29]:
num = 5
square_num = num * num
print (square_num)

25

Using a for loop, print only the odd numbers between 10 and 20.

In [35]:
for i in range(10,20):
 if i %2 != 0:  #checks if i in the range is a multiple of 2 which is an even number
  print (i) #if odd, print values of i

11
13
15
17
19

book = {
"Title": "Python for Beginners",
"Author": "Jane Doe",
"Year": 2020
}
Do the following:
● Print the book's title and year.
● Change the Year to 2023.
● Add a new key called Publisher with value "TechBooks Ltd."
● Remove the Author key.

In [ ]:
# I dont know

Write a program that takes a temperature value as input.
If the temperature is:
● 30°C and above, print "It's hot!"
● 20°C to 29°C, print "Weather is moderate."
● Below 20°C, print "It's cold!"

In [45]:
temp = 28
if temp >= 30:
  print ("It's hot")
elif temp >=20 and temp <= 29:
    print("weather is moderate")
else:
    print("it's cold")

weather is moderate

Word Length Calculator
Store any sentence of your choice in a variable and:
● Count the number of characters excluding spaces.
● Print the result.

In [51]:
text = "I like plantain and eggs"
print (len(text))
text2 = ["I like plantain and eggs"]
print (len(text2))

24
1